stages:
  prepare:
    cmd: python -m src.prepare
    deps:
    - data/raw/test.csv
    - data/raw/train.csv
    - src/prepare.py
    params:
    - prepare.random_state
    - prepare.test_size
    - prepare.train_size
    outs:
    - data/processed/X_train.csv
    - data/processed/X_valid.csv
    - data/processed/y_train.csv
    - data/processed/y_valid.csv
  train:
    cmd: python -m src.train
    deps:
    - data/processed/X_train.csv
    - data/processed/y_train.csv
    - src/train.py
    params:
    - train.algorithm
    - train.random_state
    outs:
    - models/iowa_model.pkl
  evaluate:
    cmd: python -m src.evaluate
    deps:
    - data/processed/X_valid.csv
    - data/processed/y_valid.csv
    - models/iowa_model.pkl
    - src/evaluate.py
    metrics:
    - metrics/scores.json:
        cache: false
