[tool.poetry]
name = "mlops2023course-demo"
version = "0.1.0"
description = "Demo project for the Machine Learning Systems in Production (MLOps) course."
authors = ["Santiago del Rey <santiago.del.rey@upc.edu>"]
readme = "README.md"
packages = [{include = "mlops2023course_demo"}]

[tool.poetry.dependencies]
python = ">3.9,<3.12"
pandas = "^2.0.3"
scikit-learn = "^1.2.2"

[tool.poetry.group.dev.dependencies]
dvc = "<3.0"
mlflow = "^2.4.1"
black = "^23.3.0"
isort = "^5.12.0"
bandit = "^1.7.5"
pylint = "^2.17.4"
pytest = "^7.4.0"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
